<a href="https://colab.research.google.com/github/RuwaAbey/PyTorch-Learning/blob/main/PyTorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import numpy as np

**LISTS**

In [4]:
my_list1 = [1,2,3,4,5] #one dimensional array
my_list1

#multi dimensional array
my_list2 = [[1,2,3,4,5],[6,7,8,9,10]]
my_list2

[[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]]

**NUMPY ARRAY**

In [5]:
np1 = np.random.rand(3,4)
np1

array([[0.28661383, 0.08265223, 0.97675363, 0.77365272],
       [0.48988473, 0.32743877, 0.55618281, 0.34592569],
       [0.4577141 , 0.22939459, 0.42496404, 0.91269956]])

In [6]:
np1.dtype

dtype('float64')

**TENSORS**

In [12]:
tensor_2d = torch.randn(3,4)
tensor_2d
#tensor_2d.dtype

tensor([[ 1.4354, -0.0704, -0.6789, -0.4745],
        [ 0.1693,  0.2924,  1.2418,  2.2035],
        [ 0.6672, -0.1567,  0.6291, -0.7654]])

In [8]:
tensor_3d = torch.zeros(2,3,4)
tensor_3d

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [17]:
##Create tensor out of numpy array
tensor_3d = torch.tensor(np1)
tensor_3d

tensor([[0.2866, 0.0827, 0.9768, 0.7737],
        [0.4899, 0.3274, 0.5562, 0.3459],
        [0.4577, 0.2294, 0.4250, 0.9127]], dtype=torch.float64)

In [19]:
my_torch = torch.arange(10)
my_torch

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [20]:
#Reshape and View
my_torch = my_torch.reshape(2,5) #Given shape should goes with the data
my_torch

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [23]:
#Reshape if we don't know the number of items using -1
my_torch2 = torch.arange(10)
my_torch2

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [25]:
my_torch2 = my_torch2.reshape(2,-1)
my_torch2

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [27]:
my_torch2 = my_torch.reshape(-1,5)
my_torch2

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [28]:
my_torch3 = torch.arange(10)
my_torch3

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [32]:
my_torch3 = my_torch3.view(2,5)
my_torch3
#view and reshape does the same thing

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])