<a href="https://colab.research.google.com/github/RuwaAbey/PyTorch-Learning/blob/main/Tensor_Math_Operations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Tensor math operations**



*   Add Substract, Multiply, Divide, Reaminders, Exponents
*   Shorthand and uh, Longhand
*   Reassignment






In [7]:
import torch
import numpy as np

In [8]:
tensor_a = torch.tensor([1,2,3,4,5])
tensor_b = torch.tensor([6,7,8,9,10])

**Addition**

In [9]:
tensor_a + tensor_b

tensor([ 7,  9, 11, 13, 15])

In [10]:
#Addition Longhand
torch.add(tensor_a,tensor_b)

tensor([ 7,  9, 11, 13, 15])

**Substraction**

In [11]:
tensor_a - tensor_b

tensor([-5, -5, -5, -5, -5])

In [12]:
#Sub Function
torch.sub(tensor_a,tensor_b)

tensor([-5, -5, -5, -5, -5])

**Multipication**

In [13]:
tensor_a * tensor_b

tensor([ 6, 14, 24, 36, 50])

In [14]:
#Sub function
torch.mul(tensor_a,tensor_b)

tensor([ 6, 14, 24, 36, 50])

**Division**

In [15]:
tensor_a/tensor_b

tensor([0.1667, 0.2857, 0.3750, 0.4444, 0.5000])

In [17]:
#Div Longhand
torch.div(tensor_a,tensor_b)

tensor([0.1667, 0.2857, 0.3750, 0.4444, 0.5000])

**Remainders**

In [18]:
tensor_a % tensor_b

tensor([1, 2, 3, 4, 5])

In [19]:
#Remainder longhand
torch.remainder(tensor_a, tensor_b)

tensor([1, 2, 3, 4, 5])

**Exponents/power**

In [20]:
#Exponent/power
torch.pow(tensor_a, tensor_b)

tensor([      1,     128,    6561,  262144, 9765625])

In [21]:
#Another way to write longhand
tensor_a.add(tensor_b)

tensor([ 7,  9, 11, 13, 15])

**Reassignment**

In [22]:
tensor_a + tensor_b

tensor([ 7,  9, 11, 13, 15])

In [24]:
#tensor_a = tensor_a + tensor_b
tensor_a.add(tensor_b)

tensor([ 7,  9, 11, 13, 15])

In [25]:
tensor_a

tensor([1, 2, 3, 4, 5])