<a href="https://colab.research.google.com/github/RuwaAbey/PyTorch-Learning/blob/main/Introduction/PyTorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
import numpy as np

**LISTS**

In [ ]:
my_list1 = [1,2,3,4,5] #one dimensional array
my_list1

#multi dimensional array
my_list2 = [[1,2,3,4,5],[6,7,8,9,10]]
my_list2

[[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]]

**NUMPY ARRAY**

In [ ]:
np1 = np.random.rand(3,4)
np1

array([[0.58303897, 0.51233015, 0.61859268, 0.65118268],
       [0.58118706, 0.32788325, 0.74438855, 0.53636534],
       [0.97800551, 0.4830008 , 0.72235967, 0.36227427]])

In [ ]:
np1.dtype

dtype('float64')

**TENSORS**

In [ ]:
tensor_2d = torch.randn(3,4)
tensor_2d
#tensor_2d.dtype

tensor([[ 0.5353,  0.8222,  0.1649,  1.4119],
        [ 1.1757,  1.3133,  0.6363,  0.6019],
        [-0.2292, -1.4519,  0.3481,  1.5712]])

In [ ]:
tensor_3d = torch.zeros(2,3,4)
tensor_3d

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [ ]:
##Create tensor out of numpy array
tensor_3d = torch.tensor(np1)
tensor_3d

tensor([[0.5830, 0.5123, 0.6186, 0.6512],
        [0.5812, 0.3279, 0.7444, 0.5364],
        [0.9780, 0.4830, 0.7224, 0.3623]], dtype=torch.float64)

**Reshape Tensor**

In [ ]:
my_torch = torch.arange(10)
my_torch

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
#Reshape and View
my_torch = my_torch.reshape(2,5) #Given shape should goes with the data
my_torch

#Note:Reshape must match numbers

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

**Reshape with -1**

If you do not sure of the shape to match numbers you can use -1.

In [ ]:
#Reshape if we don't know the number of items using -1
my_torch2 = torch.arange(10)
my_torch2

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
my_torch2 = my_torch2.reshape(2,-1)
my_torch2

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [ ]:
my_torch2 = my_torch2.reshape(-1,5)
my_torch2

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

**Reshape vs View**

In [ ]:
my_torch3 = torch.arange(10)
my_torch3

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
my_torch4 = my_torch3.view(2,5)
my_torch4
#view and reshape does the same thing

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [ ]:
#with reshape and view they will update
my_torch5 = torch.arange(10)
my_torch5

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
my_torch6 = my_torch5.reshape(2,5)
my_torch6

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [ ]:
my_torch5[1] = 4141
my_torch5

tensor([   0, 4141,    2,    3,    4,    5,    6,    7,    8,    9])

In [ ]:
my_torch6

tensor([[   0, 4141,    2,    3,    4],
        [   5,    6,    7,    8,    9]])

**Slices**

In [ ]:
my_torch7 = torch.arange(10)
my_torch7

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
#Grab a specific item
my_torch7[7]

tensor(7)

In [ ]:
#Grab slice
my_torch8 = my_torch7.reshape(5,2)
my_torch8

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])

In [ ]:
my_torch8[:,1]

tensor([1, 3, 5, 7, 9])

In [ ]:
#Return colomn
my_torch8[:,1:]

tensor([[1],
        [3],
        [5],
        [7],
        [9]])